version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    
    steps:
      - checkout

      - run:
          name: Print Repo Contents
          command: ls -la
  
  deploy:
    docker:
      - image: python:3.7-stretch
    working_directory: ~/circleci-docs
    steps:
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Test
          command: ls -la

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
              - build
          filters:
            branches:
              only: master