version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    working_directory: ~/circleci-docs
    steps:
      - checkout

      - run:
          name: Print Repo Contents
          command: ls -la
  
  deploy:
    docker:
      - image: python:3.7-stretch
    
    steps:
      - run:
        name: Install awscli
        command: sudo pip install awscli
      - run:
        name: Check awscli version
        command: aws --version

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master