version: 2
jobs:
  deploy_cfn:
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - run:
          name: List Contents
          command: ls -la
      - run:
          name: Install awscli
          command: pip install awscli
      - run:
          name: Deploy AWS Fargate Cluster Infra Stack
          command: aws cloudformation deploy --template-file ./fargatecluster_cfn.yaml --stack-name tradingCluster --capabilities CAPABILITY_IAM

workflows:
  version: 2
  deploy_fargate_infra_stack:
    jobs:
      - deploy_cfn:
          filters:
            branches:
              only: master
